# Generated by Django 4.1.2 on 2022-10-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_alter_emprestimo_nome_emprestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='co_autor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
