# Generated by Django 4.1.2 on 2022-10-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_alter_livro_co_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='nome_emprestado',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='tempo_duracao',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_cadastro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
