# Generated by Django 4.1.2 on 2022-10-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_alter_livro_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
