# Generated by Django 4.1.2 on 2022-10-17 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0012_categoria_usuario_livro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.livro'),
            preserve_default=False,
        ),
    ]
