# Generated by Django 4.1.2 on 2022-10-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0015_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='tempo_duracao',
        ),
    ]
